mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path, re_path
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pis.urls')),
    re_path(r'^accounts/login/$', LoginView.as_view(template_name='registration/login.html'), name="login"),
    re_path(r'^accounts/logout/$', LogoutView.as_view(), LogoutView.next_page, name="logout"),
]

pis/urls.py
from django.conf.urls import url
from . import views
from django.urls import path, re_path
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy


app_name = 'pis'
urlpatterns = [
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    url(r'^register/$', views.register, name='register'),
    # change password urls
    path('password_change/',
         auth_views.PasswordChangeView.as_view(success_url=reverse_lazy('pis:password_change_done')),
         name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset/', auth_views.PasswordResetView.as_view(success_url=reverse_lazy('pis:password_reset_done')),
         {'email_template_name': 'registration/password_reset_email.html'}, name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(success_url=reverse_lazy('pis:password_reset_complete')),
         name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('', views.home, name='home'),
    re_path(r'^home/$', views.home, name='home'),
    path('product_list', views.product_list, name='product_list'),
    path('product/create/', views.product_new, name='product_new'),
    path('product/<int:pk>/edit/', views.product_edit, name='product_edit'),
    path('product/<int:pk>/delete/', views.product_delete, name='product_delete'),
    path('supplier_list', views.supplier_list, name='supplier_list'),
    path('supplier/create/', views.supplier_new, name='supplier_new'),
    path('supplier/<int:pk>/edit/', views.supplier_edit, name='supplier_edit'),
    path('supplier/<int:pk>/delete/', views.supplier_delete, name='supplier_delete'),
    path('purchaseorder_list', views.purchaseorder_list, name='purchaseorder_list'),
    path('purchaseorder/create/', views.purchaseorder_new, name='purchaseorder_new'),
    path('purchaseorder/<int:pk>/edit/', views.purchaseorder_edit, name='purchaseorder_edit'),
    path('purchaseorder/<int:pk>/delete/', views.purchaseorder_delete, name='purchaseorder_delete'),
    path('billingorder_list', views.billingorder_list, name='billingorder_list'),
    path('billingorder/create/', views.billingorder_new, name='billingorder_new'),
    path('billingorder/<int:pk>/edit/', views.billingorder_edit, name='billingorder_edit'),
    path('billingorder/<int:pk>/delete/', views.billingorder_delete, name='billingorder_delete'),

]

pis/models.py
from django.db import models

# Create your models here.

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

Inventory={
    ('AVAILABLE','Item ready to be purchased'),
    ('SOLD','Item already purchased'),
    ('RESTOCKING','Item needs restocking in few days')
}
class Product(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='products',null=True)
    productname = models.CharField(max_length=100)
    producttype = models.CharField(max_length=100,blank=False)
    price = models.IntegerField()
    status = models.CharField(max_length=20,choices=Inventory,default='AVAILABLE')
    comments = models.CharField(max_length=60,default="No Issues")
    quantity = models.IntegerField(blank=False, null=False,default="50")
    created_date = models.DateTimeField(
        default=timezone.now)
    updated_date = models.DateTimeField(default=timezone.now)

    def created(self):
        self.created_date = timezone.now()
        self.save()

    def updated(self):
        self.updated_date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.productname)

class Supplier(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='suppliers',null=True)
    #product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='suppliers')
    suppliername = models.CharField(max_length=100)
    supplieraddress = models.CharField(max_length=100,blank=True, null=True)
    suppliercity = models.CharField(max_length=20,blank=True, null=True)
    supplierstate = models.CharField(max_length=20,blank=True, null=True)
    supplierzipcode = models.CharField(max_length=10,blank=True, null=True)
    created_date = models.DateTimeField(
        default=timezone.now)
    updated_date = models.DateTimeField(default=timezone.now)

    def created(self):
        self.created_date = timezone.now()
        self.save()

    def updated(self):
        self.updated_date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.suppliername)

class PurchaseOrder(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='purchaseorders')
    orderId = models.IntegerField()
    productname = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='purchaseorders')
    # suppliername = models.ForeignKey(Supplier,on_delete=models.CASCADE, related_name='purchaseorders')
   #  purchaseorderdate = models.DateTimeField(default=timezone.now)
    numberordered = models.IntegerField()
    created_date = models.DateTimeField(
        default=timezone.now)
    updated_date = models.DateTimeField(default=timezone.now)

    def created(self):
        self.created_date = timezone.now()
        self.save()

    def updated(self):
        self.updated_date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.orderId)


class BillingOrder(models.Model):
    orderId = models.ForeignKey(PurchaseOrder, on_delete=models.CASCADE, related_name='billingorders')
    billno = models.IntegerField()
    # billdate = models.DateTimeField(default=timezone.now)
    billstatus = models.CharField(max_length=50,blank=True,null=True);
    created_date = models.DateTimeField(
        default=timezone.now)
    updated_date = models.DateTimeField(default=timezone.now)

    def created(self):
        self.created_date = timezone.now()
        self.save()

    def updated(self):
        self.updated_date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.billno)

pis/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Product,Supplier,PurchaseOrder,BillingOrder

class ProductForm(forms.ModelForm):
   class Meta:
       model = Product
       fields = ('productname', 'producttype', 'price', 'status', 'comments', 'quantity' )


class SupplierForm(forms.ModelForm):
   class Meta:
       model = Supplier
       fields = ('suppliername', 'supplieraddress', 'suppliercity', 'supplierstate', 'supplierzipcode' )

class PurchaseOrderForm(forms.ModelForm):
   class Meta:
       model = PurchaseOrder
       fields = ('user','orderId', 'productname', 'numberordered')


class BillingOrderForm(forms.ModelForm):
   class Meta:
       model = BillingOrder
       fields = ('orderId', 'billno', 'billstatus')

class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')
    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']

pis/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.contrib.auth import authenticate, login
from .models import *
from .forms import *
from django.shortcuts import render


# Create your views here.


now = timezone.now()
def home(request):
   return render(request, 'pis/home.html',
                 {'pis': home})

def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            # Create a new user object but avoid saving it yet
            new_user = user_form.save(commit=False)
            # Set the chosen password
            new_user.set_password(
            user_form.cleaned_data['password'])
            # Save the User object
            new_user.save()
            return render(request, 'pis/register_done.html', {'new_user': new_user})
    else:
      user_form = UserRegistrationForm()
      return render(request, 'pis/register.html', {'user_form': user_form})

@login_required
def purchaseorder_list(request):
    purchaseorders = PurchaseOrder.objects.filter(created_date__lte=timezone.now())
    return render(request, 'pis/purchaseorder_list.html', {'purchaseorders': purchaseorders})


@login_required
def purchaseorder_new(request):
    if request.method == "POST":
        form = PurchaseOrderForm(request.POST)
        if form.is_valid():
            purchaseorder = form.save(commit=False)
            purchaseorder.created_date = timezone.now()
            purchaseorder.save()
            purchaseorders = PurchaseOrder.objects.filter(created_date__lte=timezone.now())
            return render(request, 'pis/purchaseorder_list.html',
                          {'purchaseorders': purchaseorders})
    else:
        form = PurchaseOrderForm()
    return render(request, 'pis/purchaseorder_new.html', {'form': form})


@login_required
def purchaseorder_edit(request, pk):
    purchaseorder = get_object_or_404(PurchaseOrder, pk=pk)
    if request.method == "POST":
        form = PurchaseOrderForm(request.POST, instance=purchaseorder)
        if form.is_valid():
            purchaseorder = form.save()
            purchaseorder.updated_date = timezone.now()
            purchaseorder.save()
            purchaseorders = PurchaseOrder.objects.filter(created_date__lte=timezone.now())
            return render(request, 'pis/purchaseorder_list.html', {'purchaseorders': purchaseorders})
    else:
        form = PurchaseOrderForm(instance=purchaseorder)
    return render(request, 'pis/purchaseorder_edit.html', {'form': form})


@login_required
def purchaseorder_delete(request, pk):
    purchaseorder = get_object_or_404(PurchaseOrder, pk=pk)
    purchaseorder.delete()
    return redirect('pis:purchaseorder_list')


@login_required
def billingorder_list(request):
    billingorders = BillingOrder.objects.filter(created_date__lte=timezone.now())
    return render(request, 'pis/billingorder_list.html', {'billingorders': billingorders})


@login_required
def billingorder_new(request):
    if request.method == "POST":
        form = BillingOrderForm(request.POST)
        if form.is_valid():
            billingorder = form.save(commit=False)
            billingorder.created_date = timezone.now()
            billingorder.save()
            billingorders = BillingOrder.objects.filter(created_date__lte=timezone.now())
            return render(request, 'pis/billingorder_list.html',
                          {'billingorders': billingorders})
    else:
        form = BillingOrderForm()
    return render(request, 'pis/billingorder_new.html', {'form': form})


@login_required
def billingorder_edit(request, pk):
    billingorder = get_object_or_404(BillingOrder, pk=pk)
    if request.method == "POST":
        form = BillingOrderForm(request.POST, instance=billingorder)
        if form.is_valid():
            billingorder = form.save()
            billingorder.updated_date = timezone.now()
            billingorder.save()
            billingorders = BillingOrder.objects.filter(created_date__lte=timezone.now())
            return render(request, 'pis/billingorder_list.html', {'billingorders': billingorders})
    else:
        form = BillingOrderForm(instance=billingorder)
    return render(request, 'pis/billingorder_edit.html', {'form': form})


@login_required
def billingorder_delete(request, pk):
    billingorder = get_object_or_404(BillingOrder, pk=pk)
    billingorder.delete()
    return redirect('pis:billingorder_list')


@login_required
def supplier_list(request):
    suppliers = Supplier.objects.filter(created_date__lte=timezone.now())
    return render(request, 'pis/supplier_list.html', {'suppliers': suppliers})


@login_required
def supplier_new(request):
    if request.method == "POST":
        form = SupplierForm(request.POST)
        if form.is_valid():
            supplier = form.save(commit=False)
            supplier.created_date = timezone.now()
            supplier.save()
            suppliers = Supplier.objects.filter(created_date__lte=timezone.now())
            return render(request, 'pis/supplier_list.html',
                          {'suppliers': suppliers})
    else:
        form = SupplierForm()
    return render(request, 'pis/supplier_new.html', {'form': form})


@login_required
def supplier_edit(request, pk):
    supplier = get_object_or_404(Supplier, pk=pk)
    if request.method == "POST":
        form = SupplierForm(request.POST, instance=supplier)
        if form.is_valid():
            supplier = form.save()
            supplier.updated_date = timezone.now()
            supplier.save()
            suppliers = Supplier.objects.filter(created_date__lte=timezone.now())
            return render(request, 'pis/supplier_list.html', {'suppliers': suppliers})
    else:
        form = SupplierForm(instance=supplier)
    return render(request, 'pis/supplier_edit.html', {'form': form})


@login_required
def supplier_delete(request, pk):
    supplier = get_object_or_404(Supplier, pk=pk)
    supplier.delete()
    return redirect('pis:supplier_list')


@login_required
def product_list(request):
    products = Product.objects.filter(created_date__lte=timezone.now())
    return render(request, 'pis/product_list.html', {'products': products})


@login_required
def product_new(request):
    if request.method == "POST":
        form = ProductForm(request.POST)
        if form.is_valid():
            product = form.save(commit=False)
            product.created_date = timezone.now()
            product.save()
            products = Product.objects.filter(created_date__lte=timezone.now())
            return render(request, 'pis/product_list.html',
                          {'products': products})
    else:
        form = ProductForm()
        # print("Else")
    return render(request, 'pis/product_new.html', {'form': form})


@login_required
def product_edit(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if request.method == "POST":
        form = ProductForm(request.POST, instance=product)
        if form.is_valid():
            product = form.save()
            product.updated_date = timezone.now()
            product.save()
            products = Product.objects.filter(created_date__lte=timezone.now())
            return render(request, 'pis/product_list.html', {'products': products})
    else:
        # print("else")
        form = ProductForm(instance=product)
    return render(request, 'pis/product_edit.html', {'form': form})


@login_required
def product_delete(request, pk):
    product = get_object_or_404(Product, pk=pk)
    product.delete()
    return redirect('pis:product_list')

pis/templates/pis/base.html
{% load staticfiles %}

<html lang="en">
<head>
    <title>Product Inventory Management System</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <style>


        body {
            background-color: #7abaff;
        }

        /* Remove the navbar's default margin-bottom and rounded borders */
        .navbar {
            margin-bottom: 0;
            border-radius: 0;
        }

        /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
        .row.content {
            height: 100%;
        }

        /* Set gray background color and 100% height */
        .sidenav {
            padding-top: 20px;
            background-color: #6f42c1;
            height: 100%;
        }

        /* Set black background color, white text and some padding */
        footer {
            background-color: #005cbf;
            color: white;
            padding: 15px;
        }

        /* On small screens, set height to 'auto' for sidenav and grid */
        @media screen and (max-width: 767px) {
            .sidenav {
                height: auto;
                padding: 15px;
            }

            .row.content {
                height: auto;
            }
        }
    </style>
</head>
<body id="app-layout">
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">

            <!-- Collapsed Hamburger -->
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#myNavbar">
                <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>


        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav">
                <li style="padding-left: 50px">
                    <a class="navbar-brand"  href="/"><img width="72px" height="34px" src="{% static "images/Logo.png" %}"> </a>
                        <a class ="navbar-brand" href="/" id="pis"><b>Product Inventory Management System</b></a>
                </li>

                {% if user.groups.all.0.name == "Supplier" %}
                    <li><a href="{% url 'pis:purchaseorder_list' %}">Purchase Orders</a></li>
                    <li><a href="{% url 'pis:billingorder_list' %}">Billing Orders</a></li>
                {% else %}
                <li><a href="{% url 'pis:product_list' %}">Products</a></li>
                <li><a href="{% url 'pis:supplier_list' %}">Suppliers</a></li>
                <li><a href="{% url 'pis:purchaseorder_list' %}">Purchase Orders</a></li>
                <li><a href="{% url 'pis:billingorder_list' %}">Billing Orders</a></li>
            {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                     <a class="navbar-brand" href="#">{{user.username }}</a>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="{% url 'logout' %}"><i class="fa fa-btn fa-sign-out"></i>Logout</a></li>
                            <li><a href="{% url 'pis:password_change' %}"><i class="fa fa-btn fa-sign-out"></i>Change Password</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<div class="content container">


    <div class="row">
        <div class="col-md-8">
            {% block content %}
                <div class="links">
                    <!-- Example row of columns -->
                    <div class="row">

                        <div class="col-md-3">
                            <div class="thumbnail">
                                <img src="{% static "images/products.jpg" %}" alt="product"/>
                                <div class="caption">
                                    <h2>Products</h2>
                                    {% if user.is_authenticated %}
                                        <p><a class="btn btn-default" href="{% url 'pis:product_list' %}"
                                              role="button">View
                                            product details </a></p>
                                    {% endif %}
                                </div>
                            </div>
                        </div>

                        <div class="col-md-3">
                            <div class="thumbnail">
                                <img src="{% static "images/supplier.jpg" %}" alt="supplier"/>
                                <div class="caption">
                                    <h2>Suppliers</h2>
                                    <p><a class="btn btn-default" href="{% url 'pis:supplier_list' %}"
                                           role="button">View
                                        supplier details </a></p>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="thumbnail">
                                <img src="{% static "images/purchase-order.jpg" %}" alt="purchaseorder"/>
                                <div class="caption">
                                    <h2>Purchase Orders</h2>
                                    <p><a class="btn btn-default" href="{% url 'pis:purchaseorder_list' %}" role="button">View
                                        purchase order details </a></p>
                                </div>
                            </div>
                        </div>

                     <div class="col-md-3">
                            <div class="thumbnail">
                                <img src="{% static "images/billingorder.jpg" %}" alt="billingorder"/>
                                <div class="caption">
                                    <h2>Billing Orders</h2>
                                    <p><a class="btn btn-default" href="{% url 'pis:billingorder_list' %}" role="button">View
                                        billing order details</a></p>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            {% endblock %}
        </div>
    </div>
</body>
</html>

pis/templates/pis/billingorder_delete.html
{% extends 'pis/base.html' %}
 {% block body_block %}
    <h1>Delete {{ billingorder.billno }}?</h1>

    <form method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete">
        <a href="{% url 'pis:home' pk=billingorder.billno %} ">Cancel</a>

    </form>

{% endblock %}

pis/templates/pis/billingorder_edit.html
{% extends 'pis/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

    <h1>Edit Billing Order</h1>
    <form method="POST" class="billingorder-form">{% csrf_token %}
        {{ form|crispy }}
        <button type="submit"  class="save btn btn-primary">Update</button>
    </form>
{% endblock %}

pis/templates/pis/billingorder_new.html
{% extends 'pis/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

    <h1>Create a Billing Order</h1>
    <form method="POST" class="billingorder-form">{% csrf_token %}
          {{ form|crispy }}
        <br>
        <button type="submit" align="center" class="save btn btn-primary">Save</button>
    </form>
{% endblock %}

pis/templates/pis/product_edit.html
{% extends 'pis/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

    <h1>Edit Product</h1>
    <form method="POST" class="product-form">{% csrf_token %}
        {{ form|crispy }}
        <button type="submit"  class="save btn btn-primary">Update</button>
    </form>
{% endblock %}

pis/templates/pis/product_list.html
{% extends 'pis/base.html' %}
{% block content %}
    <html>
    <head>
        <meta charset="UTF-8">
        <title>Product Inventory Management</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

    </head>

     <style>

         body {
            background-color: #7abaff;
        }

    </style>
    <body>

    <div class="row">
        <h2 style="padding-left: 15Px">Product Information</h2>
    </div>
    <div >
        <table class="table table-striped table-bordered table-hover" >
            <thead>
            <tr class="bg-info">
                <th>Product Name</th>
                <th>Product Type</th>
                <th>Price</th>
                <th>Quantity</th>
                <th>Status</th>
                <th>Comments</th>
                <th colspan="3">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for product in products %}
                <tr>
                    <td class="nowrap">{{ product.productname }}</td>
                    <td class="nowrap">{{ product.producttype }}</td>
                     <td class="nowrap">{{ product.price }}</td>
                    <td class="nowrap">{{ product.quantity }}</td>
                    <td class="nowrap">{{ product.status }}</td>
                    <td class="nowrap">{{ product.comments }}</td>
                    <td class="nowrap"><a href="{% url 'pis:product_edit' pk=product.pk %}"
                           class="btn btn-warning">Edit</a></td>
                    <td class="nowrap"><a href="{% url 'pis:product_delete' pk=product.pk %}"
                           onclick="return confirm('Are you sure you want to delete?')"
                           class="btn btn-danger">Delete</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <div class="row" align="center">
            <a href="{% url 'pis:product_new' %}" class="row"><span
                    class="btn btn-primary">Add Product</span></a>
        </div>
    </div>
    </body>
    </html>
{% endblock %}

pis/templates/pis/product_new.html
{% extends 'pis/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

    <h1>Add a New Product</h1>
    <form method="POST" class="product-form">{% csrf_token %}
          {{ form|crispy }}
        <br>
        <button type="submit" align="center" class="save btn btn-primary">Save</button>
    </form>
{% endblock %}

pis/templates/pis/purchaseorder_list.html
{% extends 'pis/base.html' %}
{% block content %}
    <html>
    <head>
        <meta charset="UTF-8">
        <title>Product Inventory Management</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

    </head>

     <style>

         body {
            background-color: #7abaff;
        }

    </style>
    <body>


    <div class="row">
        <h2 style="padding-left: 15Px">Purchase Order Information</h2>
    </div>
    <div >
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr class="bg-info">
                <th>Order Id</th>
                <th>Product Name</th>
                <th>Number Ordered</th>
                {% if user.groups.all.0.name != "Supplier" %}
                <th colspan="3">Actions</th>
                {% endif %}
            </tr>
            </thead>
            <tbody>
            {% for porders in purchaseorders %}
                <tr>
                    <td class="nowrap">{{ porders.orderId }}</td>
                    <td class="nowrap">{{ porders.productname }}</td>
                    <td class="nowrap">{{ porders.numberordered }}</td>
                    {% if user.groups.all.0.name != "Supplier" %}
                    <td class="nowrap"><a href="{% url 'pis:purchaseorder_edit' pk=porders.pk %}"
                           class="btn btn-warning">Edit</a></td>
                    <td class="nowrap"><a href="{% url 'pis:purchaseorder_delete' pk=porders.pk %}"
                           onclick="return confirm('Are you sure you want to delete?')"
                           class="btn btn-danger">Delete</a>
                    </td>
                {% endif %}

                </tr>
            {% endfor %}
            </tbody>
        </table>
        {% if user.groups.all.0.name != "Supplier" %}
        <div class="row" align="center">
            <a href="{% url 'pis:purchaseorder_new' %}" class="row"><span
                    class="btn btn-primary">Create Purchase Order</span></a>
        </div>
     {% endif %}
    </div>
    </body>
    </html>
{% endblock %}

pis/templates/pis/purchaseorder_new.html
{% extends 'pis/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

    <h1>Create a Purchase Order</h1>
    <form method="POST" class="purchaseorder-form">{% csrf_token %}
          {{ form|crispy }}
        <br>
        <button type="submit" align="center" class="save btn btn-primary">Save</button>
    </form>
{% endblock %}

pis/templates/pis/supplier_list.html
{% extends 'pis/base.html' %}
{% block content %}
    <html>
    <head>
        <meta charset="UTF-8">
        <title>Product Inventory Management</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

    </head>
    <body>

     <style>

         body {
            background-color: #7abaff;
        }

    </style>


    <div class="row">
        <h2 style="padding-left: 15Px">Supplier Information</h2>
    </div>
    <div style="height: auto" >
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr class="bg-info">
                <th>Supplier Name</th>
                <th>Address</th>
                <th>City</th>
                <th>State</th>
                <th>Zip Code</th>
                <th colspan="3">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for supplier in suppliers %}
                <tr>
                    <td>{{ supplier.suppliername }}</td>
                    <td>{{ supplier.supplieraddress }}</td>
                     <td>{{ supplier.suppliercity }}</td>
                    <td>{{ supplier.supplierstate }}</td>
                    <td>{{ supplier.supplierzipcode }}</td>
                    <td><a href="{% url 'pis:supplier_edit' pk=supplier.pk %}"
                           class="btn btn-warning">Edit</a></td>
                    <td><a href="{% url 'pis:supplier_delete' pk=supplier.pk %}"
                           onclick="return confirm('Are you sure you want to delete?')"
                           class="btn btn-danger">Delete</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <div class="row" align="center">
            <a href="{% url 'pis:supplier_new' %}" class="row"><span
                    class="btn btn-primary">Add Supplier</span></a>
        </div>
    </div>
    </body>
    </html>
{% endblock %}